sudo: required
services:
  - docker
language: elixir
elixir:
  - 1.6.6
  - 1.7.3
otp_release:
  - 20.3
  - 21.1
before_script:
  - docker run -d --name=dev-consul -e CONSUL_BIND_INTERFACE=eth0 -p 8500:8500 consul
  - sleep 5
